networks:
    dbcontroller: {}
services:
  influxdb:
    image: influxdb:latest
    container_name: influxdb2
    networks:
        - dbcontroller
    volumes:
      - ./config:/etc/influxdb2
      - ./data:/var/lib/influxdb2
    ports:
      - 8086:8086
    restart: unless-stopped